/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 dryad_wood_guardian.glb --transform 
Files: dryad_wood_guardian.glb [622.92KB] > C:\Users\Ismael\Desktop\Template de réalité augmenté\frontend\public\models\dryad_wood_guardian-transformed.glb [80.14KB] (87%)
Author: M_Thimmig (https://sketchfab.com/M_Thimmig)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dryad-wood-guardian-de5515e29b0649f7aa3ebf3e7a1d6357
Title: Dryad Wood Guardian
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/dryad_wood_guardian-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.vines_Gradiente_0.geometry} material={materials.Gradiente} position={[-0.097, 2.99, 0.608]} rotation={[-1.621, 0, 0]} />
      <mesh geometry={nodes.vines_Line_0.geometry} material={materials.Line} position={[-0.097, 2.99, 0.608]} rotation={[-1.621, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/dryad_wood_guardian-transformed.glb')
