/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 low_poly_nature.glb --transform 
Files: low_poly_nature.glb [10.28MB] > C:\Users\Ismael\Desktop\Template de réalité augmenté\frontend\public\models\low_poly_nature-transformed.glb [497.4KB] (95%)
Author: EdwinRC (https://sketchfab.com/Edwin3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-nature-493b488007f14e3b98502ccc60f78582
Title: Low Poly Nature
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/low_poly_nature-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.PaletteMaterial003} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/low_poly_nature-transformed.glb')
